[package]
name = "tokio-stream"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
pretty_env_logger = "0.2.5"
lapin-futures = "0.14.0"
serde_json = "1.0.32"
futures = "0.1.25"
tokio = "0.1.11"
